include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: false
    prefer_final_fields: false
    use_key_in_widget_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors_in_immutables: false
    avoid_print: false
    # these are only rules only copy paste these according to the folders and then read its about 2o min task but you will learn a lot from these codelabs also read the docs 
    #  jo easy lagay wo kar lo sir asif ki videos aur yeh codelabs because dono hi recommended hayn